spring.application.name=fileUpload

spring.datasource.url=jdbc:postgresql://localhost:5432/fileuplode
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#spring.profiles.active=dev

file.base-url=http://localhost:8080/api


file.upload-dir=uploads



spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

# Jackson infinite recursion fix
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.indent_output=true
spring.jackson.default-property-inclusion=NON_NULL

server.forward-headers-strategy=framework

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.remote-ip-header=x-forwarded-for

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.example.fileupload=DEBUG

# Security sozlamalari (upload uchun ruxsat)